routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});

Auth::routes();*/

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/language','HomeController@Changelang');

Route::group(['prefix'=>'admin','middleware'=>'admin'],function () {

Route::get('/', 'HomeController@index')->name('home');

// Advertisment  route
    Route::resource('/adv', 'admin\AdvertismentController');

  // category route
    Route::resource('/category', 'Admin\CategoryController');

    //Blog   route
    Route::resource('/blog', 'admin\BlogController');

     //testomanial   route
    Route::resource('/testomanial', 'admin\TestimonialController');

         //account route
    Route::resource('/account', 'admin\Acounts_controller');

     Route::resource('permission', 'PermissionController');
       Route::resource('role', 'RoleController');  
      



    // Product  route
    Route::resource('/product', 'admin\ProductController');
      Route::get('/product1', 'admin\ProductController@index1');
    Route::get('/pindingproduct/{id}', 'admin\ProductController@pindingproduct')->name('pindingproduct');
    Route::get('/activeproduct/{id}', 'admin\ProductController@activeproduct')->name('activeproduct');


//offer route
 Route::resource('/offer', 'admin\OfferController');

//setting
     //Route::resource('/seetting', 'admin\SeettingController');
    Route::resource('/about', 'admin\AboutController');


    //notification
     Route::get('/shownotification', 'admin\NotificationController@shownotification')->name('shownotification');
    Route::post('/sendnotification', 'admin\NotificationController@sendnotification')->name('sendnotification');
     

});











$this->get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login');
$this->get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
     public function image()
    {
        return $this->hasMany('App\ProductImage','product_id');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\admin;

use App\Category;
use App\Product;
use App\ProductImage;
use App\ProductLanguage;
use App\SubCategory;
use App\SubCategoryLanguage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use File;
use Session;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products=array();
        $lang=Session::get('locale');
        $products =Product::
            join('product_languages', 'product_languages.product_id', '=', 'products.id')
            ->join('category_languages', 'category_languages.categore_id', '=', 'products.categore_id')
            ->select('products.*','product_languages.name','product_languages.descreption','category_languages.name as category_name')
            ->where('category_languages.language_id',$lang)
            ->where('product_languages.language_id',$lang)
            ->where('products.type','=','1')
            ->get();

              for ($i=0;$i<count($products);$i++)
        {
           $images=ProductImage::select('image')->where('product_id',$products[$i]->id)->first();
            $products[$i]['id']=$products[$i]->id;
            $products[$i]['category_name']=$products[$i]->category_name;
            $products[$i]['name']=$products[$i]->name;
            $products[$i]['descreption']=$products[$i]->descreption;
            $products[$i]['created_at']=$products[$i]->created_at;
            $products[$i]['image']=$images['image'];
        }
         

  // dd($products);
        return view('admin.product.index',compact('products'));
    }

        public function index1()
    {
        $products=array();
        $lang=Session::get('locale');
        $products =Product::
            join('product_languages', 'product_languages.product_id', '=', 'products.id')
            ->join('category_languages', 'category_languages.categore_id', '=', 'products.categore_id')
            ->select('products.*','product_languages.name','product_languages.descreption','category_languages.name as category_name')
            ->where('category_languages.language_id',$lang)
            ->where('product_languages.language_id',$lang)
            ->where('products.type','=','0')
            ->get();


              for ($i=0;$i<count($products);$i++)
        {
            $images=ProductImage::select('image')->where('product_id',$products[$i]->id)->first();
            $products[$i]['id']=$products[$i]->id;
            $products[$i]['category_name']=$products[$i]->category_name;
            $products[$i]['name']=$products[$i]->name;
            $products[$i]['descreption']=$products[$i]->descreption;
            $products[$i]['created_at']=$products[$i]->created_at;
            $products[$i]['image']=$images['image'];
        }
    // dd($products);
        return view('admin.product.index1',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lang=Session::get('locale');
        $category = DB::table('categories')
            ->join('category_languages', 'category_languages.categore_id', '=', 'categories.id')
            ->select('categories.id as ids','category_languages.*')
            ->where('category_languages.language_id',$lang)
            ->get();
        return view('admin.product.add',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $product=new Product();
        $product->categore_id=$request->input('categore_id');
        $product->p_price=$request->input('p_price');
         $product->c_price=$request->input('c_price');
         $product->alt=$request->input('alt');
        $product->des=$request->input('des');
       
         $product->type=$request->input('type');
          $product->offer=$request->input('offer');
    
        $product->save();
        $product_id=$product->id;
        $productlang=new ProductLanguage();
        $productlang->product_id=$product_id;
        $productlang->name=$request->name;
        $productlang->language_id=1;
        $productlang->descreption=$request->descreption;
        $productlang->save();
        $productlang=new ProductLanguage();
        $productlang->product_id=$product_id;
        $productlang->name=$request->productnameenglish;
        $productlang->language_id=2;
        $productlang->descreption=$request->productdescreptionenglish;
        $productlang->save();
        $product_id=$product->id;
        $allimages = $request->image;
        if ($request->hasFile('image')) {
            foreach ($allimages as $file) {
                $img=new ProductImage();
                $extension = $file->getClientOriginalExtension();
                $name = sha1($file->getClientOriginalName());
                $imgname = date('y-m-d') . $name . "." . $extension;
                $path = storage_path('app/product/');
                $file->move($path, $imgname);
                $img->image = 'product'.'/'.$imgname;
                $img->product_id=$product_id;
                $img->save();
            }
           //dd(   $allimages);

        }
        return redirect('/admin/product')->with('add', 'Add Adv successfully');   
      
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {
        //
}
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lang=Session::get('locale');
        $product = DB::table('products')
            ->join('product_languages', 'product_languages.product_id', '=', 'products.id')
            ->join('product_images', 'product_images.product_id', '=', 'products.id')
            ->select('products.*','product_languages.name','product_languages.descreption','product_images.image as image')
            ->where('products.id',$id)
            ->where('product_languages.language_id',$lang)
            ->get();
           // dd($product);
        $category = DB::table('categories')
            ->join('category_languages', 'category_languages.categore_id', '=', 'categories.id')
            ->select('category_languages.*')
            ->where('category_languages.language_id',$lang)
            ->get();
           // dd($product);

             // $image = ProductImage::where('product_id', $id)->get();
          
         //dd(  $image);



        return view('admin.product.edit',compact('product','category','image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    //    return $request->all();
        $product=Product::find($id);
        $product->categore_id=$request->input('categore_id');
          $product->p_price=$request->input('p_price');
        $product->c_price=$request->input('c_price');
         $product->offer=$request->input('offer');
        $product->save();
        $product_id= $product->id;
        $pr_lang=ProductLanguage::where('product_id',$product_id)->get();
        $productlanguage=ProductLanguage::find($pr_lang[0]['id']);
        $productlanguage->name=$request->name;
        if (isset($request->descreption)) {
            $productlanguage->descreption=$request->descreption;
        }
        $productlanguage->save();
        $productlanguage1=ProductLanguage::find($pr_lang[1]['id']);
        $productlanguage1->name=$request->productnameenglish;
        $productlanguage1->descreption=$request->productdescreptionenglish;
        $productlanguage1->save();

           $allimages = $request->image;
        if ($request->hasFile('image')) {
            $image = ProductImage::where('product_id', $id)->get();
            for ($i = 0; $i < count($image); $i++) {
                $image_path = "storage/app/" . $image[$i]['image'];  // Value is not URL but directory file path
                if (File::exists($image_path)) {
                    File::delete($image_path);
                }
                $im=ProductImage::find($image[$i]['id']);
                $im->destroy($image[$i]['id']);
            }
            foreach ($allimages as $file) {
                $img=new ProductImage();
                $extension = $file->getClientOriginalExtension();
                $name = sha1($file->getClientOriginalName());
                $imgname = date('y-m-d') . $name . "." . $extension;
                $path = storage_path('app/product/');
                $file->move($path, $imgname);
                $img->image = 'product'.'/'.$imgname;
                $img->product_id=$product_id;
                $img->save();
            }
           // dd(  $image);
        }
     
        return redirect('/admin/product')->with('update', 'category Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $image = ProductImage::where('product_id', $id)->get();
        for ($i = 0; $i < count($image); $i++) {
            $image_path = "storage/app/" . $image[$i]['image'];  // Value is not URL but directory file path
            if (File::exists($image_path)) {
                File::delete($image_path);
            }
        }
        $product->destroy($id);
        return redirect('/admin/product')->with('delete', 'product deleted successfully');

resources/views/admin/product/index.blade.php
@extends('layouts.cpanellayout')
@section('title')
    {{trans('app.product')}}
@endsection

@section('header')
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url('admin')}}">{{trans('app.home')}}</a></li>
                    <li class="breadcrumb-item active">{{trans('app.product2')}}</li>
                </ol>
            </div>
            <div class="col-md-7 col-4 align-self-center">
                <div class="d-flex m-t-10 justify-content-end">
                    <div class="">
                        <button class="right-side-toggle waves-effect waves-light btn-success btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                    </div>
                </div>
            </div>
        </div>
        @if (\Session::has('add'))
            <div class="col-xs-12">
                <div class="alert alert-success">
                    <button type="button" class="close pull-left" data-dismiss="alert">x</button>
                    <strong>Success!</strong> تم الاضافة بنجاح
                </div>
            </div>
        @endif
        @if (\Session::has('pinding'))
            <div class="col-xs-12">
                <div class="alert alert-success">
                    <button type="button" class="close pull-left" data-dismiss="alert">x</button>
                    <strong>Success!</strong> تم اخفاء المنتج بنجاح
                </div>
            </div>
        @endif
        @if (\Session::has('active'))
            <div class="col-xs-12">
                <div class="alert alert-success">
                    <button type="button" class="close pull-left" data-dismiss="alert">x</button>
                    <strong>Success!</strong> تم اظهار المنتج بنجاح
                </div>
            </div>
        @endif
        @if (\Session::has('update'))
            <div class="col-xs-12">
                <div class="alert alert-success">
                    <button type="button" class="close pull-left" data-dismiss="alert">x</button>
                    <strong>Success!</strong> تم تعديل بنجاح
                </div>
            </div>
        @endif
        @if (\Session::has('delete'))
            <div class="col-xs-12">
                <div class="alert alert-success">
                    <button type="button" class="close pull-left" data-dismiss="alert">x</button>
                    <strong>Success!</strong>  تم الحذف بنجاح
                </div>
            </div>
        @endif
        <div class="row">

            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="">
                            <a href="{{route('product.create')}}">
                                <button class=" btn-success btn  btn-lg pull-left m-l-10">{{trans('app.add')}}</button>
                            </a><br><br>
                        </div>
                        <div class="table-responsive m-t-40">
                            <table id="myTable" class="table display table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th> {{trans('app.id')}}</th>
                                    <th> {{trans('app.cat')}} </th>
                                    <th> {{trans('app.productname')}} </th>
                                    <th>{{trans('app.productdescreption')}}  </th>
                                    <th> {{trans('app.productimage')}} </th>
                                    <th> price before  </th>
                                    <th> price after  </th>
                                    
                                    
                                    <th>{{trans('app.controll')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php $id=1; ?>
                                @for($i=0;$i<count($products);$i++)
                                <tr>
                                    <td>{{$id}}</td>
                                    <td>{{$products[$i]['category_name']}}
                                    </td>
                                    <td>{{$products[$i]['name']}}</td>
                                    <td>{!!$products[$i]['descreption']!!}</td>
                                    <td>
                                        <a href="{{url('storage/app/'.$products[$i]['image'])}}" onclick="window.open(this.href, '_blank', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;">
                                            <img src="{{url('storage/app/'.$products[$i]['image'])}}" style="width: 150px; height: 90px;" alt="homepage" class="light-logo" />
                                        </a>
                                        <td>{{$products[$i]['p_price']}}</td>
                                        <td>{{$products[$i]['c_price']}}</td>
                                        
                                       
                                    </td>
                                    
                                    <td>
                                       
                                         @if($products[$i]['pinding'] == 1)
                                        <a href="{{route('pindingproduct',$products[$i]['id'])}}" class="btn btn-primary"  title="الغاء تمييز المنتج " onclick="return confirm('هل تريد الغاء تمييز المنتج ')">
                                            <i class="mdi mdi-eye"></i>
                                        </a>
                                        @endif

                                        @if($products[$i]['pinding'] == 0)
                                            <a href="{{route('activeproduct',$products[$i]['id'])}}" class="btn btn-primary" title=" تمييز المنتج" onclick="return confirm('هل تريد تمييز المنتج ')">
                                                <i class="mdi mdi-eye-off"></i>
                                            </a>
                                        @endif
                                       
                                        <a href="{{route('product.edit',$products[$i]['id'])}}" class="btn btn-warning" >
                                            <i class="fas fa-edit"></i>
                                        </a>

                                        
                                       
                                        <a><form action="{{route('product.destroy',$products[$i]['id'])}}" style="display: inline;" method="POST" accept-charset="utf-8">
                                                {{csrf_field()}}
                                                {{method_field('DELETE')}}
                                                <button onclick="return confirm('Are you sure you want to Delete item?')" type="submit" class="btn btn-danger">
                                                    <i class="fas fa-archive"></i>
                                                </button>
                                            </form></a>
                                       
                                    </td>
                                </tr>
                                    <?php $id+=1;?>
                                @endfor
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer')
    <script src="{{url('resources/assets/plugins/js/jquery.dataTables.min.js') }}"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <!-- end - This is for export functionality only -->
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
            $(document).ready(function() {
                var table = $('#example').DataTable({
                    "columnDefs": [{
                        "visible": false,
                        "targets": 2
                    }],
                    "order": [
                        [2, 'asc']
                    ],
                    "displayLength": 25,
                    "drawCallback": function(settings) {
                        var api = this.api();
                        var rows = api.rows({
                            page: 'current'
                        }).nodes();
                        var last = null;
                        api.column(2, {
                            page: 'current'
                        }).data().each(function(group, i) {
                            if (last !== group) {
                                $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                                last = group;
                            }
                        });
                    }
                });
                // Order by the grouping
                $('#example tbody').on('click', 'tr.group', function() {
                    var currentOrder = table.order()[0];
                    if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                        table.order([2, 'desc']).draw();
                    } else {
                        table.order([2, 'asc']).draw();
                    }
                });
            });
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
@endsection