routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});

Auth::routes();*/

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/language','HomeController@Changelang');

Route::group(['prefix'=>'admin','middleware'=>'admin'],function () {

Route::get('/', 'HomeController@index')->name('home');

// Advertisment  route
    Route::resource('/adv', 'admin\AdvertismentController');

  // category route
    Route::resource('/category', 'Admin\CategoryController');

    //Blog   route
    Route::resource('/blog', 'admin\BlogController');

     //testomanial   route
    Route::resource('/testomanial', 'admin\TestimonialController');

         //account route
    Route::resource('/account', 'admin\Acounts_controller');

     Route::resource('permission', 'PermissionController');
       Route::resource('role', 'RoleController');  
      



    // Product  route
    Route::resource('/product', 'admin\ProductController');
      Route::get('/product1', 'admin\ProductController@index1');
    Route::get('/pindingproduct/{id}', 'admin\ProductController@pindingproduct')->name('pindingproduct');
    Route::get('/activeproduct/{id}', 'admin\ProductController@activeproduct')->name('activeproduct');


//offer route
 Route::resource('/offer', 'admin\OfferController');

//setting
     //Route::resource('/seetting', 'admin\SeettingController');
    Route::resource('/about', 'admin\AboutController');


    //notification
     Route::get('/shownotification', 'admin\NotificationController@shownotification')->name('shownotification');
    Route::post('/sendnotification', 'admin\NotificationController@sendnotification')->name('sendnotification');
     

});











$this->get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login');
$this->get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\EntrustPermission;
class Permission extends EntrustPermission
{
    protected $table = "permissions";
    protected $fillable = ['name', 'display_name', 'description','created_at','updated_at'];
     public function role()
    {
        return $this->belongsToMany('App\Role');
    }
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permission;
use DB;

class PermissionController extends Controller {

    public function index() {
        $permissions = Permission::all();
        return view('admin.permission.index', compact('permissions'));
    }

    public function create() {
        return view('admin.permission.create');
    }

    public function store(Request $request) {

        $newPermission = new Permission;
        $newPermission->name = $request->name;
        $newPermission->description = $request->description;
        $newPermission->display_name = $request->display_name;
        $newPermission->save();
        return redirect()->route('permission.index')->withMessage('You Have Successfully Created a Role');
    }

    public function edit($id) {
        //
        $editPermission = Permission::find($id);
 
        return view('admin.permission.edit', compact('editPermission'));
    }
 public function update(Request $request, $id) {
        //
        $permissions = Permission::find($id);
        $permissions->name = $request->name;
        $permissions->display_name = $request->display_name;
        $permissions->description = $request->description;
        $permissions->save();
       
        return redirect()->route('permission.index')->withMessage('Role Updated');
    }
    
        public function destroy($id) {
        //
        //$role = Role::find($id);
        DB::table('permissions')->where('id', $id)->delete();
        // $role->delete();

        return back()->withMessage('Role Deleted');
    }

    public function assighRole() {
        $user = User::where('name', '=', 'Admin')->first();


        // or eloquent's original technique
        $done = $user->roles()->attach($user->id); // id only
        // return($done);
    }
}

resources/views/admin/permission/create.blade.php
@extends('layouts.cpanellayout')
@section('title')
    اضافه صلاحيات
@endsection

@section('header')

@endsection
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content">



    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif


    <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                     <div class="row page-titles">
                            <div class="col-md-5 col-8 align-self-center">
                                <h3 class="text-themecolor m-b-0 m-t-0">Forms</h3>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url('admin')}}">الرئيسيه</a></li>
                                    <li class="breadcrumb-item"><a href="{{url('admin/permission')}}">الصلاحيات</a> </li>
                                    <li class="breadcrumb-item active">اضافة </li>
                                </ol>
                            </div>
                        </div>
                    <!-- general form elements -->
                <div class="box box-primary">

                    <!-- /.box-header -->
                    <!-- form start -->
                    <form action="{{route('permission.store')}}" method="post" role="form" accept-charset="utf-8">
                        {{csrf_field()}}
                        <div class="card card-body col-md-12">
                            <div class="form-group col-md-12">
                                <label for="name"> الاسم <span style="color:red;">*</span>:</label>
                                <input name="name" type="text" class="form-control" id="name" placeholder="" required="required"/>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="display_name"> ضع اسم <span style="color:red;">*</span>:</label>
                                <input name="display_name" type="text" class="form-control" id="display_name" placeholder="" required="required"/>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="description"> الوصف  <span style="color:red;">*</span>:</label>
                                <input name="description" type="text" id="descreption" class="form-control" id="description" placeholder="" required="required"/>
                            </div>
                            <div class="form-group m-b-0">
                                <div class="offset-sm-3 col-sm-9">
                                    <button type="submit" class="btn btn-info waves-effect waves-light m-t-10 pu">اضافه</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
            <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<script src="{{url('/vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>

{{--
<script src="{{ url('resources/assets/tinymce/js/tinymce/tinymce.min.js') }}"></script>
--}}
<script>
     CKEDITOR.replace('descreption');
$(document).ready(function () {
    $('#genpass').click(function () {
        var randomstring = Math.random().toString(36).slice(-8);
        $('#password').val(randomstring);
        $('#password-confirm').val(randomstring);
        $('#custmessage').addClass('col-sm-4');
        $('#custmessage').addClass('alert-success');
        $('#custmessage').html('The generated password will be sent to your email');
    });
});
</script>
@endsection

resources/views/admin/permission/edit.blade.php
@extends('layouts.cpanellayout')
@section('title')
    اضافه صلاخيات
@endsection

@section('header')

@endsection
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content">
<!-- Content Wrapper. Contains page content -->
<div class="content">


    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="row page-titles">
                    <div class="col-md-5 col-8 align-self-center">
                        <h3 class="text-themecolor m-b-0 m-t-0  text-center">تعديل  بيانات الصلاحيات </h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('admin')}}">الرئيسيه</a></li>
                            <li class="breadcrumb-item"><a href="{{url('admin/permission')}}">الصلاحيات</a> </li>
                            <li class="active">
                                {{$editPermission->name}}
                            </li>
                        </ol>
                    </div>
                    <div class="col-md-7 col-4 align-self-center">
                        <div class="d-flex m-t-10 justify-content-end">

                            <div class="">
                                <button class="right-side-toggle waves-effect waves-light btn-success btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- general form elements -->
                <div class="box box-primary">

                    <!-- /.box-header -->
                    <!-- form start -->
                    <form action="{{route('permission.update',$editPermission->id)}}" method="post" role="form" accept-charset="utf-8">
                        {{method_field('PATCH')}}
                        {{csrf_field()}}
                        <div class="card card-body col-md-12">
                            <div class="form-group col-md-12">
                                <label for="name"> الاسم <span style="color:red;">*</span>:</label>
                                <input name="name" type="text" class="form-control" value="{{$editPermission->name}}" id="name" placeholder="" required="required"/>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="display_name"> ضع اسم <span style="color:red;">*</span>:</label>
                                <input name="display_name" type="text" value="{{$editPermission->display_name}}" class="form-control" id="display_name" placeholder="" required="required"/>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="description"> الوصف  <span style="color:red;">*</span>:</label>
                                <input name="description" type="text"  value="{{$editPermission->description}}" class="form-control" id="descreption" placeholder="" required="required"/>
                            </div>
                            <div class="form-group m-b-0">
                                <div class="offset-sm-3 col-sm-9">
                                    <button type="submit" class="btn btn-info waves-effect waves-light m-t-10 pu">اضافه</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
            <!-- /.row -->
        </div>
    </section>
    <!-- /.content -->
</div>
<script src="{{url('/vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>

<script src="admin/tinymce/js/tinymce/tinymce.min.js"></script>
<script>
    CKEDITOR.replace('descreption');
$(document).ready(function () {
    $('#genpass').click(function () {
        var randomstring = Math.random().toString(36).slice(-8);
        $('#password').val(randomstring);
        $('#password-confirm').val(randomstring);
        $('#custmessage').addClass('col-sm-4');
        $('#custmessage').addClass('alert-success');
        $('#custmessage').html('The generated password will be sent to your email');
    });
});
</script>
@endsection

resources/views/admin/permission/index.blade.php
@extends('layouts.cpanellayout')
@section('title')
    All permision
@endsection

@section('header')
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
               
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url('admin')}}"> الرئيسيه</a></li>
                    <li class="breadcrumb-item active">كل الصلاحيات </li>
                </ol>
            </div>
            <div class="col-md-7 col-4 align-self-center">
                <div class="d-flex m-t-10 justify-content-end">

                    <div class="">
                        <button class="right-side-toggle waves-effect waves-light btn-success btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="">
                            <a href="{{route('permission.create')}}">
                                <button class=" btn-success btn  btn-lg pull-left m-l-10">اضافه بيانات جديده </button>
                            </a><br><br>
                        </div>
                        <div class="table-responsive m-t-40">
                            <table id="myTable" class="table display table-bordered table-striped">
                                <thead>
                                <tr>
                                    <td> name </td>
                                    <td> display_name </td>
                                    <td> description </td>
                                    <td> Action </td>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($permissions as $permission)
                                    <tr>
                                        <td>{{$permission->name}}</td>
                                        <td>{{$permission->display_name}}</td>
                                        <td>{{$permission->description}}</td>
                                        <td>
                                            <a href="{{route('permission.edit',$permission->id)}}" class="btn btn-warning" >
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a><form action="{{route('permission.destroy',$permission->id)}}" style="display: inline;" method="POST" accept-charset="utf-8">
                                                    {{csrf_field()}}
                                                    {{method_field('DELETE')}}
                                                    <button onclick="return confirm('Are you sure you want to Delete item?')" type="submit" class="btn btn-danger">
                                                        <i class="fas fa-archive"></i>
                                                    </button>
                                                </form></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer')
    <script src="{{url('resources/assets/plugins/js/jquery.dataTables.min.js') }}"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <!-- end - This is for export functionality only -->
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
            $(document).ready(function() {
                var table = $('#example').DataTable({
                    "columnDefs": [{
                        "visible": false,
                        "targets": 2
                    }],
                    "order": [
                        [2, 'asc']
                    ],
                    "displayLength": 25,
                    "drawCallback": function(settings) {
                        var api = this.api();
                        var rows = api.rows({
                            page: 'current'
                        }).nodes();
                        var last = null;
                        api.column(2, {
                            page: 'current'
                        }).data().each(function(group, i) {
                            if (last !== group) {
                                $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                                last = group;
                            }
                        });
                    }
                });
                // Order by the grouping
                $('#example tbody').on('click', 'tr.group', function() {
                    var currentOrder = table.order()[0];
                    if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                        table.order([2, 'desc']).draw();
                    } else {
                        table.order([2, 'asc']).draw();
                    }
                });
            });
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
@endsection