routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});

Auth::routes();*/

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/language','HomeController@Changelang');

Route::group(['prefix'=>'admin','middleware'=>'admin'],function () {

Route::get('/', 'HomeController@index')->name('home');

// Advertisment  route
    Route::resource('/adv', 'admin\AdvertismentController');

  // category route
    Route::resource('/category', 'Admin\CategoryController');

    //Blog   route
    Route::resource('/blog', 'admin\BlogController');

     //testomanial   route
    Route::resource('/testomanial', 'admin\TestimonialController');

         //account route
    Route::resource('/account', 'admin\Acounts_controller');

     Route::resource('permission', 'PermissionController');
       Route::resource('role', 'RoleController');  
      



    // Product  route
    Route::resource('/product', 'admin\ProductController');
      Route::get('/product1', 'admin\ProductController@index1');
    Route::get('/pindingproduct/{id}', 'admin\ProductController@pindingproduct')->name('pindingproduct');
    Route::get('/activeproduct/{id}', 'admin\ProductController@activeproduct')->name('activeproduct');


//offer route
 Route::resource('/offer', 'admin\OfferController');

//setting
     //Route::resource('/seetting', 'admin\SeettingController');
    Route::resource('/about', 'admin\AboutController');


    //notification
     Route::get('/shownotification', 'admin\NotificationController@shownotification')->name('shownotification');
    Route::post('/sendnotification', 'admin\NotificationController@sendnotification')->name('sendnotification');
     

});











$this->get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login');
$this->get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    //
}

app/Adv.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Adv extends Model
{
    //
}

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    //
}

app/BlogLanguage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BlogLanguage extends Model
{
    //
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Product;

class Category extends Model
{
    public function product()
    {
        return $this->belongsTo('App\Product','categore_id');
    }
}

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    //
}

app/Favirate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Favirate extends Model
{
    //
}

app/Language.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    protected $table = "languages";
}

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    //
}

app/Offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
     public function product()
    {
        return $this->hasMany('App\OfferProduct','product_id');
    }
}

app/OfferProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OfferProduct extends Model
{
    protected $table = "offer_products";
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
}

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\EntrustPermission;
class Permission extends EntrustPermission
{
    protected $table = "permissions";
    protected $fillable = ['name', 'display_name', 'description','created_at','updated_at'];
     public function role()
    {
        return $this->belongsToMany('App\Role');
    }
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
     public function image()
    {
        return $this->hasMany('App\ProductImage','product_id');
    }
}

app/ProductImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductImage extends Model
{
    //
}

app/RateProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RateProduct extends Model
{
    //
}

app/Role.php
<?php

namespace App;

use Zizaco\Entrust\EntrustRole;
use Illuminate\Database\Eloquent\Model;

class Role extends EntrustRole
{
    //use EntrustRole;
    
   /* public function __construct()
    {

        $this->EntrustRole = new EntrustRole;
    }*/
   protected $fillable = ['name', 'display_name', 'description','created_at','updated_at'];

     public function permision()
    {
        return $this->belongsToMany('App\Permission');
    }
     public function users()
    {
        return $this->belongsToMany('App\User','role_user','role_id','user_id');
    }
}

app/RoleUser.php
<?php

namespace App;

use Zizaco\Entrust\EntrustRole;
use Illuminate\Database\Eloquent\Model;

class RoleUser extends Model {

    // use EntrustRole;
    //
    /*public function __construct()
      {

      $this->EntrustRole = new EntrustRole;
      }*/
    protected $table = "role_user";

 

}

app/Testimonial.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Testimonial extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable ;
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function roles() {
        return $this->belongsToMany('App\Role','role_user', 'user_id','role_id');
    }

    public function authorizeRoles($roles)
    {
        if ($this->hasAnyRole($roles)) {
            return true;
        }
        abort(401, 'This action is unauthorized.');
    }
    public function hasAnyRole($roles)
    {
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
        } else {
            if ($this->hasRole($roles)) {
                return true;
            }
        }
        return false;
    }
}

resources/views/admin/accounts/create.blade.php
@extends('layouts.cpanellayout')
@section('title')
    {{trans('app.account')}}
@endsection

@section('header')

@endsection
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content">
    <!-- Content Header (Page header) -->
    @if (\Session::has('message'))
        <div class="col-xs-12">
            <div class="alert alert-success">
                <button type="button" class="close pull-left" data-dismiss="alert">x</button>
                <strong>فشل في الانتقال  !</strong>لا تملك الصلاحيه
            </div>
        </div>
@endif
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <button type="button" class="close pull-left" data-dismiss="alert">x</button>
                <strong>خطاء!</strong> رجاء ادخال بيانات صحيحه<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    <!-- Main content -->
        <!-- Main content -->
        <section class="content">
            <!-- left column -->
            <div class="col-md-12">
                <div class="row page-titles">
                    <div class="col-md-5 col-8 align-self-center">
                        <h3 class="text-themecolor m-b-0 m-t-0">Forms</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('admin')}}"> {{trans('app.home')}}</a></li>
                            <li class="breadcrumb-item"><a href="{{url('admin/account')}}"> {{trans('app.account')}} </a> </li>
                            <li class="breadcrumb-item active">اضافة </li>
                        </ol>
                    </div>
                </div>
                <!-- general form elements -->
                <div class="box box-primary">

                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form"  action="{{route('account.store')}}" method="post" enctype="multipart/form-data">
                        {{ csrf_field () }}
                        <div class="card card-body col-md-12">
                            <div class="form-group">
                                <label for="exampleInputEmail1"> Name</label>
                                <input required type="text" class="form-control" name="name" id="exampleInputEmail1">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">  Email</label>
                                <input class="form-control" rows="8" required name="email"  type="email">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">  Password</label>
                                <input name="row_password"  id="password" type="password" class="form-control"  required="required"/>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Confirm Password</label>
                                <input name="remember_token"  id="password-confirm" type="password" class="form-control" required="required"/>

                            </div>
                            <div id='custmessage'>
                            </div>
                            <div class="col-sm-12 form-group">
                                @foreach($roles as $role)
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="role_name[]" value="{{$role->id}}" style="position: initial;right: -9999px;opacity: 1;">
                                        <span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
                                        {{$role->name}}
                                    </label>
                                </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="form-group m-b-0">
                            <div class="offset-sm-3 col-sm-9">
                                <button type="submit" class="btn btn-info waves-effect waves-light m-t-10 pu"> {{trans('app.add')}}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

<script src="{{ url('resources/assets/tinymce/js/tinymce/tinymce.min.js') }}"></script>
<script>
$(document).ready(function () {
    $('#genpass').click(function () {
        var randomstring = Math.random().toString(36).slice(-8);
        $('#password').val(randomstring);
        $('#password-confirm').val(randomstring);
        $('#custmessage').addClass('col-sm-4');
        $('#custmessage').addClass('alert-success');
        $('#custmessage').html('The generated password will be sent to your email');
    });
});
</script>
@endsection

resources/views/admin/accounts/edit.blade.php
@extends('layouts.cpanellayout')
@section('title')
    {{trans('app.account')}}
@endsection

@section('header')

@endsection
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content">
        <!-- Content Header (Page header) -->
        @if (\Session::has('message'))
            <div class="col-xs-12">
                <div class="alert alert-success">
                    <button type="button" class="close pull-left" data-dismiss="alert">x</button>
                    <strong>فشل في الانتقال  !</strong>لا تملك الصلاحيه
                </div>
            </div>
    @endif
    <!-- Main content -->
        <section class="content">
            <!-- left column -->
            <div class="col-md-12">
                <div class="row page-titles">
                    <div class="col-md-5 col-8 align-self-center">
                        <h3 class="text-themecolor m-b-0 m-t-0">Forms</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('admin')}}"> {{trans('app.home')}}</a></li>
                            <li class="breadcrumb-item"><a href="{{url('admin/account')}}"> {{trans('app.account')}} </a> </li>
                            <li class="breadcrumb-item active"> {{trans('app.edit')}} </li>
                        </ol>
                    </div>
                </div>
                <!-- general form elements -->
                <div class="box box-primary">

                        <!-- /.box-header -->
                        <!-- form start -->
                        <form action="{{route('account.update',$accounts->id)}}" method="post" role="form" accept-charset="utf-8">
                            {{method_field('PATCH')}}
                            {{csrf_field()}}
                            <div class="card card-body col-md-6">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"> {{trans('app.account')}}</label>
                                    <input required type="text" value="{{$accounts->name}}" class="form-control" name="name" id="exampleInputEmail1" placeholder="Enter title">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">  {{trans('app.email')}}</label>
                                    <input class="form-control" value="{{$accounts->email}}" rows="8" required name="email" type="email">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">  {{trans('app.password')}}</label>
                                    <input name="password"  id="password" type="password" class="form-control"  placeholder="" required="required"/>

                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1"> {{trans('app.confirmpassword')}}</label>
                                    <input name="remember_token"  id="password-confirm" type="password" class="form-control"  placeholder="" required="required"/>

                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Roles</label>
                                    <select class=" col-sm-12 form-group selectpicker" name="roles">
                                        @foreach($roles as $role)
                                            <option  value="{{$role->id}}">{{$role->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group m-b-0">
                                    <div class="offset-sm-3 col-sm-9">
                                        <button type="submit" class="btn btn-info btn-block waves-effect waves-light m-t-10 pu">تعديل</button>
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

    <script src="{{ url('resources/assets/tinymce/js/tinymce/tinymce.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#genpass').click(function () {
                var randomstring = Math.random().toString(36).slice(-8);
                $('#password').val(randomstring);
                $('#password-confirm').val(randomstring);
                $('#custmessage').addClass('col-sm-4');
                $('#custmessage').addClass('alert-success');
                $('#custmessage').html('The generated password will be sent to your email');
            });
        });
    </script>
@endsection

resources/views/admin/accounts/index.blade.php
@extends('layouts.cpanellayout')
@section('title')
    {{trans('app.account')}}
@endsection

@section('header')
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url('/admin')}}"> {{trans('app.home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{url('/admin/account')}}">    {{trans('app.account')}}</a></li>
                </ol>
            </div>
            <div class="col-md-7 col-4 align-self-center">
                <div class="d-flex m-t-10 justify-content-end">
                    <div class="">
                        <button class="right-side-toggle waves-effect waves-light btn-success btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="">
                            @permission(('create'))
                            <a href="{{route('account.create')}}">
                                <button class=" btn-success btn  btn-lg pull-left m-l-10">   {{trans('app.add')}} </button>
                            </a>
                             @endpermission

                            <br><br>
                        </div>
                        <div class="table-responsive m-t-40">
                            <table id="myTable" class="table display table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>{{trans('app.id')}}</th>
                                    <th> {{trans('app.name')}}</th>
                                    <th> {{trans('app.email')}} </th>
                                    <th> {{trans('app.job')}} </th>
                                    <th> {{trans('app.controll')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php $id=1; ?>
                                @for($i=0;$i<count($collection);$i++)
                                <tr>
                                    <td>{{$id}}</td>
                                    <td>{{$collection[$i]->name}}</td>
                                    <td>{{$collection[$i]->email}}</td>
                                    <td>{{$collection[$i]->role_name}}</td>
                                    <td>
                                        
                                    @permission(('edit'))
                                        <a href="{{route('account.edit',$collection[$i]->id)}}" class="btn btn-warning" >
                                            <i class="fas fa-edit"></i>
                                        </a>
                                      @endpermission
                                     @permission(('delete'))
                                        <a><form action="{{route('account.destroy',$collection[$i]->id)}}" style="display: inline;" method="POST" accept-charset="utf-8">
                                                {{csrf_field()}}
                                                {{method_field('DELETE')}}
                                                <button onclick="return confirm('Are you sure you want to Delete item?')" type="submit" class="btn btn-danger">
                                                    <i class="fas fa-archive"></i>
                                                </button>
                                            </form></a>
                                            @endpermission
                                  
                                    </td>
                                </tr>
                                 <?php $id+=1;?>
                                @endfor
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer')
    <script src="{{url('resources/assets/plugins/js/jquery.dataTables.min.js') }}"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <!-- end - This is for export functionality only -->
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
            $(document).ready(function() {
                var table = $('#example').DataTable({
                    "columnDefs": [{
                        "visible": false,
                        "targets": 2
                    }],
                    "order": [
                        [2, 'asc']
                    ],
                    "displayLength": 25,
                    "drawCallback": function(settings) {
                        var api = this.api();
                        var rows = api.rows({
                            page: 'current'
                        }).nodes();
                        var last = null;
                        api.column(2, {
                            page: 'current'
                        }).data().each(function(group, i) {
                            if (last !== group) {
                                $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                                last = group;
                            }
                        });
                    }
                });
                // Order by the grouping
                $('#example tbody').on('click', 'tr.group', function() {
                    var currentOrder = table.order()[0];
                    if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                        table.order([2, 'desc']).draw();
                    } else {
                        table.order([2, 'asc']).draw();
                    }
                });
            });
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
@endsection

resources/views/admin/admin_login.blade.php
<!DOCTYPE html>
<html lang="en">
    
<head>
        <title>Matrix Admin</title><meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{{ asset('css/backend_css/bootstrap.min.css') }}" />
		<link rel="stylesheet" href="{{ asset('css/backend_css/bootstrap-responsive.min.css') }}" />
        <link rel="stylesheet" href="{{ asset('css/backend_css/matrix-login.css') }}"/>
        <link href="{{ asset('fonts/backend_fonts/css/font-awesome.css') }}" rel="stylesheet" />
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

    </head>
    <body>
        <div id="loginbox"> 

         @if(Session::has('flash_message_error'))
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button> 
                    <strong>{!! session('flash_message_error') !!}</strong>
            </div>
        @endif   
        @if(Session::has('flash_message_success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button> 
                    <strong>{!! session('flash_message_success') !!}</strong>
            </div>
        @endif           
            <form id="loginform" class="form-vertical" method="post" action="{{url('admin')}}">{{csrf_field()}}
				 <div class="control-group normal_text"> <h3><img src="{{ asset('images/backend_images/logo.png') }}" alt="Logo" /></h3></div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_lg"><i class="icon-user"> </i></span><input type="text" name="email" placeholder="Username" />
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_ly"><i class="icon-lock"></i></span><input type="password" name="password" placeholder="Password" />
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <span class="pull-left"><a href="#" class="flip-link btn btn-info" id="to-recover">Lost password?</a></span>
                    <span class="pull-right"><input type="submit" value="Login" class="btn btn-success" /></span>
                </div>
            </form>
            <form id="recoverform" action="#" class="form-vertical">
				<p class="normal_text">Enter your e-mail address below and we will send you instructions how to recover a password.</p>
				
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_lo"><i class="icon-envelope"></i></span><input type="text" placeholder="E-mail address" />
                        </div>
                    </div>
               
                <div class="form-actions">
                    <span class="pull-left"><a href="#" class="flip-link btn btn-success" id="to-login">&laquo; Back to login</a></span>
                    <span class="pull-right"><a class="btn btn-info"/>Reecover</a></span>
                </div>
            </form>
        </div>
        
        <script src="{{ asset('backend_js/jquery.min.js') }}"></script>  
        <script src="{{ asset('backend_js/matrix.login.js') }}"></script> 
        <script src="{{ asset('js/backend_js/bootstrap.min.js') }}"></script>
    </body>

</html>

resources/views/admin/catworks/add.blade.php
@extends('layouts.cpanellayout')
@section('title')
 اضافه تصنيف جديد
@endsection

@section('header')

@endsection
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content">



        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
    @endif


    <!-- Main content -->
        <section class="content">
            <!-- left column -->
            <div class="col-md-12">
                <div class="row page-titles">
                    <div class="col-md-5 col-8 align-self-center">
                        <h3 class="text-themecolor m-b-0 m-t-0">Forms</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url('admin')}}">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a href="{{url('admin/catwork')}}">تصنيفات الاعمال السابقة  </a> </li>
                            <li class="breadcrumb-item active">اضافة </li>
                        </ol>
                    </div>
                </div>
                <!-- general form elements -->
                <div class="box box-primary">

                    <!-- /.box-header -->
                    <!-- form start -->
                    <form action="{{route('catworks.store')}}" method="post" role="form" accept-charset="utf-8" enctype="multipart/form-data"  >
                        {{csrf_field()}}
                        <div class="card card-body col-md-6">
                            <div class="form-group">
                                <label class="control-label">اسم التصنف<span style="color:red;">*</span>:</label>
                                <div class="controls">
                                  <input type="text" name="name" id="category_name" class="form-control" id="name" placeholder=" اسم التصنف" required >
                                </div>
                            </div>
                            
                            <div class="form-group m-b-0">
                                <div class="offset-sm-3 col-sm-9">
                                    <button type="submit" class="btn btn-info waves-effect waves-light m-t-10 pu">اضافه</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

    <script src="{{url('/vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>

    

@endsection